version: "3.8"

services:
  web:
    container_name: chs_cloud_frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - PORT=5000
    restart: always
    volumes:
      - ./build:/usr/local/apache2/htdocs/
