export default {
  // Const Program Variable
  appTitle: "Cakrasoft App",
  intervalAuditDateSync: 3600000,
  defaultSystemCode: "H",
  isError: false,
  isMultiTab: true,
  nullDate: "0001-01-01T00:00:00Z",
  constCityOtherCode: "OTH",
  companyCodePrefix: "C",
  formType: {
    floorPlan: "FP",
    reservation: "R",
    guestInHouse: "I",
    folioHistory: "H",
    masterFolio: "M",
    deskFolio: "D",
    guestGroup: "GG",
    housekeeping: "HK",
    availability: "A",
    roomAvailability: "RA",
    autoPostTransaction: "APT",
    transaction: "T",
    lostAndFound: "LF",
    arCityLedger: "CL",
    arCityLedgerInvoice: "CLI",
    breakfastControl: "BFC",
    arCityLedgerInvoicePayment: "CLIP",
    bankTransaction: "BT",
    bankReconciliation: "BR",
    apCommissionAndOther: "APC",
    incomeBudget: "IB",
    budgetStatistic: "BS",
    bedType: "CFGBDTP",
    guestType: "CFGGSTTYP",
    guestTitle: "CFGGSTTTL",
    roomAmenities: "CFGRMAMNTS",
    pabxRate: "CFGPABXRT",
    memberPointType: "CFGMMBRPNTTYP",
    roomType: "CFGRMTP",
    department: "CFGDPTMN",
    subDepartment: "CFGSBDPTMN",
    taxAndService: "CFGTAS",
    accountSubGroup: "CFGASG",
    roomBoy: "CFGRB",
    roomUnavailableReason: "CFGRMULRS",
    owner: "CFGOWNR",
    journalAccountSubGroup: "CFGJNLACNSGP",
    journalAccountCategory: "CFGJNLACNCTGRY",
    journalAccount: "CFGJNLACCNT",
    country: "CFGCNTRY",
    state: "CFGSTTE",
    regency: "CFGRGNC",
    city: "CFGCTY",
    nationality: "CFGNTLTY",
    language: "CFGLNGAG",
    roomView: "CFGRMVW",
    idCardType: "CFGIDCRDTP",
    paymentType: "CFGPYMNTTP",
    marketCategory: "CFGMRKTCTGRY",
    market: "CFGMRKT",
    marketing: "CFGMRKTNG",
    cardBank: "CFGCRDBNK",
    creditCardCharge: "CFGCRDTCRDCHRG",
    bookingSource: "CFGBKSRC",
    sales: "CFGSLS",
    memberOutletDiscount: "CFGMBROTLTDSC",
    voucherReason: "CFGVCHRRSN",
    competitor: "CFGCMPTTR",
    account: "CFGACNT",
    room: "CFGRM",
    bankAccount: "CFGBNKACCNT",
    companyType: "CFGCMPNYTYP",
    company: "CFGCMPNY",
    purposeOf: "CFGPRPSF",
    cardType: "CFGCRDTYP",
    currencyNominal: "CFGCRRNCYNMNL",
    currency: "CFGCRRNCY",
    roomRate: "CFGRMRTE",
    roomRateSubCategory: "CFGRMRTSBCTGRY",
    roomRateCategory: "CFGRMRTCTGRY",
    salesSegment: "CFGSLSGMNT",
    salesSource: "CFGSLSRC",
    salesTaskAction: "CFGSLTSKACTN",
    salesTaskRepeat: "CFGSLTSKRPT",
    salesTaskTag: "CFGSLTSTG",
    productCategory: "CFGPRDCTGRY",
    productGroup: "CFGPRDCTGRP",
    product: "CFGPRDCT",
    userGroupOutlet: "CFGPRUSRGRPOTLT",
    table: "CFGTBLE",
    spaRoom: "CFGSPARM",
    waitress: "CFGWTRSS",
    printer: "CFGPRNTR",
    discountLimit: "CFGDSCNTLMNT",
    shippingAddress: "CFGSHPPNGDDRSS",
    uom: "CFGUOM",
    store: "CFGSTR",
    competitorCategory: "CFGCMPTTRCTGRY",
    itemCategory: "CFGITMCTGRY",
    posPaymentGroup: "CFGPSPYMNTGRP",
    item: "CFGITM",
    inventoryItem: "CFGINTRYITM",
    loanItem: "CFGLNITM",
    tableType: "CFGTBLETYP",
    returnStockReason: "CFGRTNSTCKRSN",
    marketList: "CFGMRKTLST",
    faManufacture: "CFGFAMNFCTR",
    faLocation: "CFGFALCTION",
    faItem: "CFGFAITM",
    phoneBookType: "CFGPHNBKTYP",
    faItemCategory: "CFGFAITMCTGRY",
    outlet: "CFGOTLT",
    tenan: "CFGTNN",
    posMarket: "CFGPSMRKT",
    itemGroup: "CFGITMGRP",
    apRefundDeposit: "APRFNDPST",
    receipt: "RCPT",
    expenseBudget: "EXPNBDGGG",
    manPower: "MNPWR",
    stockTransfer: "STCKTRNFR",
    prepaidExpense: "PRPDEXPNS",
    receive: "RCV",
    guestLoanItem: "GLT",
    PaymentApArList: "PAAL",
    cashSalesReconciliation: "CSR",
    foreignCash: "FC",
    receiptAccounting: "RACC",
    costRecipe: "CRCAMS",
    costing: "CCAMS",
    journal: "JRL",
    credit: "CRDT",
    debit: "DBT",
    accountPayable: "ACP",
    accruedExpense: "AEXP",
    accruedIncome: "AINC",
    purchaseOrder: "PROR",
    supplier: "SPLR",
    shipping: "SHPNG",
    guestProfile: "GP01",
    storeStock: "SSCAMS",
    allStoreStock: "ASSCAMS",
    fixedAssetList: "FALCAMS",
    depreciation: "CAMSD",
    returnStock: "CAMSRS",
    updateUSRForm: "UUSRF",
    venueGroup: "BNQVNGRP",
    venueCombine: "BNQVNCMBN",
    dayendClose: "DYCLOD",
    venue: "BNQVN",
    seatingPlan: "BNQSTNGPLN",
    dynamicRate: "DRTE",
    roomRateLastDeal: "RRLD",
    // TODO New Menu
    proposalAndTaskCalendar: "PSLNTSKCLNDR",
    activityLog: "ACTVTYLG",
    salesActivity: "SAM",
    taskTable: "SAMT",
    proposalTable: "PPLTBL",
    notesTable: "NTSTBL",
    activityLogTable: "ACVTLGTBL",
    sendReminderTable: "SRMDTBL",
    contactTable: "CTTBL",
    phoneBook: "PB",
    notifTpTemplate: "CFGNTTPTMPLT",
    salesActivityDashboard: "SLSACTVDSB",
    closeMonth: "ACCCM",
    closeYear: "ACCCY",
    reservationListForm: "BNQRLF",
    booking: "BNQBK",
    banquetInProgress: "BNQBKIPG",
    theme: "CFGBNQTHME",
    layout: "CFGBNQLYT",
    banquetView: "BNQBV",
    costingPos: "CLPOS",
    journalNotBalance: "ACCJNB",
    paymentByAPARList: "PBAPARL",
  },
  logUserAction: {
    // Folio
    voidTransaction: "30114",
    transferTransaction: "30116",
    moveRoom: "30120",
    // House Keeping
    readyRoom: "40101",
    cleanRoom: "40102",
    dirtyRoom: "40103",
  },
  // UserInfo
  userInfo: {
    id: 0,
    code: "",
    email: "",
    groupCode: "",
  },
  // Mode Data
  modeData: {
    insert: 0,
    edit: 1,
    tracking: 2,
    delete: 3,
    duplicate: 4,
    checkIn: 5,
    insertPayment: 6,
    insertDetail: 7,
    returned: 8,
    change: 9,
  },
  modePayroll: {
    detail: 11,
    save: 12,
    submit: 13,
    generate: 14,
    disbursement: 15,
    draft: 16,
    approve: 17,
    reject: 18,
    ready: 19,
    remark: 20,
    print: 21,
    download: 22,
    processing: 23,
    complete: 24,
    prorate: 25,
    component: 26,
    process: 27,
    back: 28,
    next: 29,
    saveAndBack: 30,
    return: 31,
    methodSelection: 32,
    downloadSelection: 33,
  },
  modeBreakdown: {
    insert: "00",
    edit: "11",
    tracking: "22",
  },
  modeBusinessSource: {
    insert: "000",
    edit: "111",
    tracking: "222",
  },
  modeCurrency: {
    insert: "0000",
    edit: "1111",
    tracking: "2222",
  },
  modeDataName: {
    insert: "Insert ",
    edit: "Edit ",
    tracking: "Tracking Data ",
  },
  modeDeposit: {
    cash: 11,
    card: 12,
    other: 13,
    refund: 14,
    directBill: 15,
    transfer: 16,
    tracking: 17,
  },
  modeSelectDataPOS: {
    remove: 10,
    modifyPrice: 21,
    overridePrice: 32,
    discount: 43,
    quantity: 54,
  },
  modeTransaction: {
    cash: 11,
    card: 12,
    other: 13,
    refund: 14,
    directBill: 15,
    transfer: 16,
    tracking: 17,
    charge: 18,
    apTransaction: 19,
    package: 20,
    voucher: 21,
    utility: 22,
    changeCorrectionDate: 23,
  },
  modeEditorTransaction: {
    folioCharge: 0,
    folioOtherPayment: 1,
    folioCashPayment: 2,
    folioCardPayment: 3,
    folioCashRefund: 4,
    folioDirectBill: 5,
    depositOtherPayment: 6,
    depositCashPayment: 7,
    depositCardPayment: 8,
    depositCashRefund: 9,
    folioAPTransaction: 10,
  },
  subFolioGroups: [
    { Code: "All", Name: "All Sub Folio" },
    { Code: "A", Name: "Sub Folio A" },
    { Code: "B", Name: "Sub Folio B" },
    { Code: "C", Name: "Sub Folio C" },
    { Code: "D", Name: "Sub Folio D" },
  ],
  roomStatus: {
    ready: "R",
    clean: "C",
    dirty: "D",
    vacantReady: "VR",
    vacantClean: "VC",
    vacantDirty: "VD",
    dontDisturb: "DD",
    doubleLock: "DL",
    houseUse: "H",
    occupied: "O",
    occupiedClean: "OC",
    occupiedDirty: "OD",
    officeUse: "OF",
    outOfOrder: "OO",
    compliment: "P",
    pleaseClean: "PC",
    sleepOut: "SO",
    underConstruction: "UC",
    vacant: "V",
  },
  roomBlockStatus: {
    generalCleaning: "G",
    showingRoom: "S",
  },

  folioType: {
    guestFolio: "F",
    masterFolio: "M",
    deskFolio: "D",
  },

  options: {
    folioTypes: [
      {
        name: "Guest Folio",
        code: "F",
      },
      {
        name: "Master Folio",
        code: "M",
      },
      {
        name: "Desk Folio",
        code: "D",
      },
    ],
    roomUnavailableStatus: [
      {
        name: "Out of Order",
        code: "OO",
      },
      {
        name: "Office User",
        code: "OF",
      },
      {
        name: "Under Construction",
        code: "UC",
      },
    ],
  },

  // modeEditorAccountTransaction: {
  //   folioCharge: 0,
  //   folioOtherPayment: 1,
  //   folioCashPayment: 2,
  //   folioCardPayment: 3,
  //   folioCashRefund: 4,
  //   deposit: 5,
  //   depositCash: 6,
  //   depositCardPayment: 7,
  //   depositCashRefund: 8,
  // },

  folioStatus: {
    open: "O",
    closed: "C",
    cancelCheckIn: "I",
  },

  roomUnavailableStatus: {
    outOfOrder: "OO",
    underConstruction: "UC",
    officeUse: "OF",
  },

  hkMode: {
    roomAvailable: "room available",
    roomUnavailable: "room unavailable",
    roomBlock: "room block",
  },
  reasonType: {
    reservation: "R",
    void: "V",
    correction: "C",
  },
  reservationStatus: {
    waitList: "W",
    new: "N",
    checkIn: "I",
    checkOut: "O",
    cancel: "C",
    noShow: "S",
    void: "V",
  },
  banquetReservationStatus: {
    reservation: "R",
    checkIn: "I",
    canceled: "C",
    noShow: "N",
    void: "V",
    checkOut: "O",
  },
  groupAccount: {
    charge: "1",
    payment: "2",
    taxService: "3",
    transfer: "4",
  },

  transactionType: {
    debit: "D",
    credit: "C",
  },

  subGroupAccount: {
    room: "ROOM",
    foodAndBeverage: "FBCH",
    roomFacilities: "RMFC",
    generalCharge: "GNRL",
    rentCharge: "RENT",
    sales: "SALE",
    accountPayable: "ACPY",
    otherCharge: "OTCH",
    cashPayment: "PYMT",
    creditOrDebitCard: "CRDB",
    bankTransfer: "BKTR",
    accountReceiveable: "ACRV",
    compliment: "CMPL",
    discount: "DSCN",
    otherPayment: "OTPY",
    taxService: "TXSV",
    transfer: "TRAN",
  },

  transfer: {
    combineAll: 1,
    transferAll: 2,
    transferSelected: 3,
  },

  subFolioGroup: ["A", "B", "C", "D"],

  subFolio: {
    A: "A",
    B: "B",
    C: "C",
    D: "D",
  },

  _CRYPTO_KEY: "^%^#@JHGHFsd56hsd63^93g$0",

  solutionCriticalErrorDayendClose: {
    autoAssign: "Auto Assign",
    checkIn: "Check In",
    cancel: "Cancel",
    changeArrival: "Change Arrival",
    noShow: "No Show",
    checkOut: "Check Out",
    extend: "Extend",
    openPos: "Open Pos",
    autoPosting: "Auto Posting",
    showFolio: "Show Folio",
    showDeposit: "Show Deposit",
    unsetWaitList: "Unset Wait List",
    openPOS: "Open POS",
  },

  mt: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
  yr: ["19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
  pageSizeOptions: [50, 100, 250, 500, 1000, 2500],

  perfectScrollbarSettings: {
    // perfectScrollbar settings
    maxScrollbarLength: 100,
    wheelSpeed: 1,
    swipeEasing: true,
  },
  // Dialog Global
  dialog: {
    typeDialog: "confirm", // alert & confirm
    isAddHeaderCloseButton: true,
  },
  dialogActions: {
    save: "save",
    delete: "delete",
    process: "process",
    submit: "submit",
    saveAndReturn: "saveAndReturn",
    complete: "complete",
  },
  accountSubGroup: {
    cashPayment: "PYMT",
    creditDebitCard: "CRDB",
    bankTransfer: "BKTR",
    compliment: "CMPL",
    accountReceivable: "ACRV",
    otherPayment: "OTPY",
    transfer: "TRAN",
    discount: "DSCN",
    accountPayable: "ACPY",
    roomCharge: "ROOM",
  },
  //
  notifPosition: "top-center",
  scaleLoadingMainLayout: 1,
  scaleLoadingContainer: 0.7,
  scaleLoadingButton: 0.4,
  iconSize: "17",
  maxNumber: 1000000000000,

  agGrid: {
    defaultGridOptions: {
      // singleClickEdit: true,
      rowGroupPanelShow: "always",
      suppressCopyRowsToClipboard: true,
      rowHeight: 26,
      headerHeight: 29,
      readOnlyEdit: true,
      onCellEditRequest: (val: any) => console.log(val),
      popupParent: document.querySelector("body"),
    },
    defaultGridOptionsPOS: {
      // singleClickEdit: true,
      suppressCopyRowsToClipboard: true,
      rowHeight: 40,
      headerHeight: 35,
      readOnlyEdit: true,
      onCellEditRequest: (val: any) => console.log(val),
      popupParent: document.querySelector("body"),
    },
    defaultGridOptionsLG: {
      // singleClickEdit: true,
      suppressCopyRowsToClipboard: true,
      rowHeight: 40,
      headerHeight: 35,
      readOnlyEdit: true,
      onCellEditRequest: (val: any) => console.log(val),
      popupParent: document.querySelector("body"),
    },
    statusBar: {
      statusPanels: [
        { statusPanel: "agTotalAndFilteredRowCountComponent", align: "left" },
        { statusPanel: "agTotalRowCountComponent", align: "center" },
        { statusPanel: "agFilteredRowCountComponent" },
        { statusPanel: "agSelectedRowCountComponent" },
        { statusPanel: "agAggregationComponent" },
      ],
    },
    // Data Grid
    dataGridShowColumnLine: false,
    dataGridShowRowLine: true,
    dataGridShowBorder: true,
    dataGridRowAlternationEnabled: false,
    // Ag grid
    rowIndexBeforeDelete: 0,
    themeAgGrid: "ag-theme-balham",
    styleAgGridFrame100:
      "width: 100%; height: 100%;minHeight:250px; overflow: auto;resize: vertical;",
    styleAgGridFrame:
      "width: 100%; height: 550px; overflow: auto;resize: vertical;",
    styleAgGridFrame3:
      "width: 100%; height: 450px; overflow: auto;resize: vertical;",
    styleAgGridFrame2:
      "width: 100%; height: 350px; overflow: auto;resize: vertical;",
    styleAgGridFrame1:
      "width: 100%; height: 250px; overflow: auto;resize: vertical;",
    styleAgGridFrame0:
      "width: 100%; height: 200px; overflow: auto;resize: vertical;",
    styleAgGridFramePackage:
      "width: 100%; height: 220px; overflow: auto;resize: vertical;",
    limitDefaultPageSize: 1000,
    paginationDataPerPage: 100,
    rowHeightReservation: 32,
    rowHeightHK: 28,
    rowHeightDefault: 26,
    headerHeight: 29,
    buttonColor: {
      cancel: "grey",
      back: "black",
      close: "grey",
      save: "primary",
      insert: "primary",
      ok: "primary",
      yes: "primary",
      no: "danger",
      checkIn: "primary",
      delete: "danger",
      createMasterFolio: "success",
      addRoutingAccount: "success",
    },
    iconActionColor: {
      menuColor: "warning",
      editColor: "success",
      correctionColor: "primary",
      deleteColor: "danger",
    },
    animatedRows: true,
    defColDef: {
      sortable: true,
      resizable: true,
      filter: true,
      editable: false,
      checkboxSelection: false,
      menuTabs: ["filterMenuTab"],
      enableRowGroup: true, // AG GRID PRO
      enablePivot: true, //AG GRID PRO
      // enableValue: true, //AG GRID PRO
    },
    colDef1: {
      sortable: true,
      resizable: true,
      filter: true,
      editable: false,
      menuTabs: ["filterMenuTab"],
      enableRowGroup: false, // AG GRID PRO
    },
  },
  // Stimulsoft Dashboard Setting
  stimulsoftReportSetting: {
    fullScreenMode: true,
    scrollbarsMode: true,
    showTooltips: false,
    showDesignButton: false,
    showAboutButton: false,
    // export
    showExportToPdf: true,
    showExportToDocument: false,
    showExportToHtml: false,
    showExportToHtml5: false,
    showExportToExcel2007: false,
    showExportToWord2007: true,
    // toolbar
    showOpenButton: false,
    showPrintButton: true,
    showSaveButton: true,
    showSendEmailButton: true,
  },
  pathReport: {
    frontDesk: "/report/reports/CHS",
    pointOfSales: "/report/reports/POS",
    banquet: "/report/reports/CBS",
    accounting: "/report/reports/CAS",
    general: "/report/reports/",
    inventoryAndAsset: "/report/reports/CAMS",
  },
  stimulsoftReportFileDirectory: {
    // Report List
    pathReport: "/report/reports/",
    // Form Report
    registrationFormReservation:
      "/report/reports/CHS/RegistrationFormReservation001.mrt",
    registrationFormInHouse:
      "/report/reports/CHS/RegistrationFormInHouse001.mrt",
    cashierReport: "/report/reports/CashierReport.mrt",
    receipt: "/report/reports/Receipt.mrt",
    receiptArCityLedgerInvoice:
      "/report/reports/ReceiptARCityLedgerInvoice.mrt",
    journalVoucher: "/report/reports/JournalVoucher002.mrt",
    journalReceipt: "/report/reports/CAS/JournalReceipt.mrt",
    journalVoucherForm: "/report/reports/JournalVoucherPaymentForm001.mrt",
    arInvoice: "/report/reports/ARInvoice.mrt",
    invoice: "/report/reports/CityLedgerInvoice001.mrt",
    receiptDeposit: "../storage/reports/ReceiptDeposit.mrt",
    receiptDepositRefund: "../storage/reports/ReceiptDepositRefund.mrt",
    receiptFolio: "/report/reports/CHS/FolioReceipt01.mrt",
    receiptFolioRefund: "/report/reports/CHS/FolioReceiptRefund01.mrt",
    miscellaneousCharge: "/report/reports/CHS/MiscellaneousCharge01.mrt",
    breakfastList: "/report/reports/CHS/BreakfastList01.mrt",
    purchaseRequest: "/report/reports/CAMS/PurchaseRequest008.mrt",
    purchaseOrder: "/report/reports/CAMS/PurchaseOrder001.mrt",
    costing: "/report/reports/CAMS/Costing.mrt",
    stockTransfer: "/report/reports/CAMS/StockTransferNew.mrt",
    receiving: "/report/reports/CAMS/ReceiveStock002.mrt",
    storeRequisition: "/report/reports/CAMS/StoreRequisition001.mrt",
    storeStockCard: "/report/reports/CAMS/StoreStockCard.mrt",
    allStoreStockCard: "/report/reports/CAMS/AllStoreStockCard.mrt",
    faPurchaseOrder: "/report/reports/CAMS/FAPurchaseOrder005.mrt",
    beoBanquet: "/report/reports/CBS/BEODefault001.mrt",
    schedulePayment: "/report/reports/CBS/SchedulePayment01.mrt",
    faReceive: "/report/reports/CAMS/FAReceive002.mrt",
    housekeepingRoomDiscrepancy:
      "/report/reports/CHS/HouseKeepingRoomDiscrepancy01.mrt",

    guestHistory: "/report/reports/CHS/GuestHistory001.mrt",
    depositReceipt: "/report/reports/CHS/DepositReceipt01.mrt",
    voucher: "/report/reports/CHS/Voucher01.mrt",

    proformaInvoice: "/report/reports/CHS/ProformaInvoice01.mrt",
    proformaInvoiceDetail: "/report/reports/CHS/ProformaInvoiceDetail001.mrt",
    confirmationLetter: "/report/reports/CHS/ConfirmationLetter001.mrt",
    cancellationLetter:
      "/report/reports/CHS/ReservationCancellationLetter001.mrt",
    folio: "/report/reports/CHS/Folio004.mrt",
    roomCheckList: "/report/reports/CHS/HousekeepingCheckList01.mrt",
    roomAttendanceControlSheet:
      "/report/reports/CHS/HousekeepingRoomAttendanceControlSheet02.mrt",

    cityLedgerInvoice: "../storage/reports/CityLedgerInvoice.mrt",
    invoicePaymentReceive: "../storage/reports/InvoicePaymentReceive.mrt",
    // /POS
    checkBill: "/report/reports/CPOS/CheckTMU220.mrt",
    captainOrder: "/report/reports/CPOS/CaptainOrderTMU220.mrt",
    captainOrderStation: "/report/reports/CPOS/CaptainOrderStationTMU220.mrt",
    tableCheck: "/report/reports/CPOS/CaptainOrderTableCheckTMU220D2.mrt",

    //General
    cashRemittance: "/report/reports/CashRemittance02.mrt",
  },

  reportList: {
    reservationList: 1001,
    waitListReservation: 1011,
    cancelledReservation: 1002,
    noShowReservation: 1003,
    voidedReservation: 1004,
    groupReservation: 1005,
    expectedArrival: 1006,
    arrivalList: 1007,
    samedayReservation: 1008,
    advancedPaymentDeposit: 1009,
    balanceDeposit: 1010,
    currentInHouse: 1501,
    guestInHouse: 1502,
    guestInHouseListing: 1508,
    guestInHousebyBusinessSource: 1503,
    guestInHousebyMarket: 1504,
    guestInHousebyBookingSource: 1510,
    guestInHousebyGuestType: 1505,
    guestInHousebyCountry: 1506,
    guestInHousebyState: 1507,
    guestInHousebyCity: 1509,
    guestInHousebyNationality: 1516,
    guestList: 1517,
    guestInHouseForecast: 1513,
    repeaterGuest: 1514,
    folioList: 1515,
    masterFolio: 1511,
    deskFolio: 1512,
    incognitoGuest: 1520,
    complimentGuest: 1521,
    houseUseGuest: 1522,
    earlyCheckIn: 1523,
    dayUse: 1524,
    earlyDeparture: 1525,
    expectedDeparture: 1526,
    extendedDeparture: 1527,
    departureList: 1528,
    actualDepartureGuestList: 1529,
    folioTransaction: 1540,
    dailyFolioTransaction: 1541,
    monthlyFolioTransaction: 1542,
    yearlyTransaction: 1543,
    chargeList: 1544,
    dailyChargeList: 1545,
    monthlyChargeList: 1546,
    yearlyChargeList: 1547,
    cashierReport: 1548,
    cashierReportReprint: 1585,
    cashSummaryReport: 1587,
    paymentBySubDepartment: 1567,
    paymentByAccount: 1568,
    paymentList: 1549,
    dailyPaymentList: 1550,
    monthlyPaymentList: 1551,
    yearlyPaymentList: 1552,
    exportCSVbyDepartureDate: 1560,
    packageSales: 1586,
    guestLedger: 1561,
    guestDeposit: 1562,
    guestAccount: 1563,
    dailySales: 1564,
    voidList: 1582,
    dailyRevenueReport: 1565,
    dailyRevenueReportSummary: 1566,
    revenueBySubDepartment: 1569,
    folioOpenBalance: 1580,
    transactionByStaff: 1588,
    taxBreakdownDetailed: 1589,
    todayRoomRevenueBreakDown: 1590,
    correction: 1581,
    cancelCheckIn: 1583,
    lostandFound: 1584,
    cancelCheckOut: 1591,
    member: 1701,
    voucher: 1702,
    voucherSRC: 1703,
    roomList: 2001,
    roomType: 2002,
    roomRate: 2003,
    roomRateBreakdown: 2021,
    roomRateStructure: 2024,
    package: 2022,
    packageBreakdown: 2023,
    roomCountSheet: 2004,
    roomCountSheetByBuildingFloorRoomType: 2011,
    roomCountSheetByRoomTypeBedType: 2012,
    roomUnavailable: 2005,
    roomSales: 2006,
    roomSalesbyRoomNumber: 2013,
    roomRevenue: 2025,
    roomHistory: 2007,
    roomTypeAvailability: 2008,
    roomTypeAvailabilityDetail: 2009,
    roomStatus: 2010,
    sales: 2501,
    salesSummary: 2502,
    frequentlySales: 2503,
    captainOrderList: 2504,
    cancelledCaptainOrder: 2505,
    cancelledCaptainOrderDetail: 2507,
    voidedCheckList: 2506,
    breakfastControl: 2508,
    guestProfile: 3001,
    frequentlyGuest: 3002,
    company: 3003,
    phoneBook: 3004,
    contractRate: 3501,
    eventList: 3502,
    reservationChart: 3503,
    reservationGraphic: 3504,
    occupiedGraphic: 3505,
    occupiedbyBusinessSourceGraphic: 3506,
    occupiedbyMarketGraphic: 3507,
    occupiedbyGuestTypeGraphic: 3508,
    occupiedbyCountryGraphic: 3509,
    occupiedbyStateGraphic: 3510,
    occupancyGraphic: 3511,
    roomAvailabilityGraphic: 3531,
    roomUnvailabilityGraphic: 3532,
    revenueGraphic: 3533,
    paymentGraphic: 3534,
    dailyStatisticReport: 3546,
    roomStatistic: 3535,
    dailyFlashReport: 3544,
    roomProduction: 3539,
    otaProductivity: 3540,
    marketStatistic: 3542,
    dailyHotelCompetitor: 3545,
    fbStatistic: 3538,
    guestForecastReport: 3536,
    guestForecastComparison: 3543,
    guestForecastReportYearly: 3541,
    cityLedgerContributionAnalysis: 3537,
    rateCodeAnalisys: 3547,
    salesContributionAnalysis: 3548,
    leadList: 3601,
    taskList: 3602,
    proposalList: 3603,
    activityLog: 3604,
    salesActivityDetail: 3605,
    cityLedgerList: 4001,
    cityLedgerAgingReport: 4002,
    cityLedgerAgingReportDetail: 4003,
    cityLedgerInvoice: 4004,
    cityLedgerInvoiceDetail: 4005,
    cityLedgerInvoicePayment: 4006,
    cityLedgerInvoiceMutation: 4007,
    bankTransactionList: 4009,
    bankTransactionAgingReport: 4010,
    bankTransactionAgingReportDetail: 4011,
    bankReconciliation: 4008,
    bankTransactionMutation: 4012,
    apRefundDepositList: 5001,
    apRefundDepositAgingReport: 5002,
    apRefundDepositAgingReportDetail: 5003,
    apRefundDepositPayment: 5004,
    apRefundDepositMutation: 5005,
    apCommissionList: 5006,
    apCommissionAgingReport: 5007,
    apCommissionAgingReportDetail: 5008,
    apCommissionPayment: 5009,
    apCommissionMutation: 5010,
    logUser: 6501,
    logShift: 6509,
    logMoveRoom: 6502,
    logVoidTransaction: 6506,
    logHouseKeeping: 6507,
    logTransferTransaction: 6503,
    logSpecialAccess: 6504,
    keyLockHistory: 6505,
    logPABX: 6508,
  },

  reportID: {
    // 8 = module / POS
    // 9 = module / CHS
    // 00 = menu
    // 00 = report
    registrationFormReservation: 90001,
    registrationFormInHouse: 90002,
    JournalVoucher: 91003,
    JournalReceipt: 91004,
    InvoicePaymentReceipt: 91005,
    JournalVoucherForm: 91006,
    Invoice: 91007,
    Invoice2: 91008,
    ARInvoice: 91009,
    PurchaseRequest: 91010,
    PurchaseOrder: 91011,
    ReceiveStock: 91012,
    StoreRequisition: 91013,
    StockTransfer: 91014,
    Costing: 91015,
    GuestHistory: 91016,
    DepositReceipt: 91017,
    StoreStockCard: 91018,
    AllStoreStockCard: 91019,
    FAPurchaseOrder: 91020,
    FAReceive: 91021,
    HouseKeepingDiscrepancy: 91022,
    Voucher: 91025,
    //Deposit
    receipt: 91000,
    receiptDeposit: 91001,
    // Reservation
    proformaInvoice: 92001,
    proformaInvoiceDetail: 92002,
    confirmationLetter: 92003,
    cancellationLetter: 91023,
    breakfastList: 91024,

    cashierReport: 20006,

    folio: 93001,
    folioReceipt: 93002,
    folioReceiptRefund: 93002,
    miscellaneousCharge: 93003,
    utilityCharge: 93004,
    //housekeeping
    roomCheckList: 94001,
    roomAttendanceControlSheet: 94002,
    //AR
    cityLedgerInvoice: 95001,
    invoicePaymentReceive: 95002,
    //POS
    checkBill: 80001,
    captainOrder: 80002,
    captainOrderStation: 80003,
    tableCheck: 80004,
    //Banquet
    beoBanquet: 91026,
    schedulePayment: 91027,
  },

  userAccessType: {
    form: "F",
    report: "R",
    special: "S",
    keylock: "K",
    reservation: "V",
    deposit: "D",
    inHouse: "I",
    walkIn: "W",
    folio: "L",
    folioHistory: "H",
    floorPlan: "P",
    company: "C",
    invoice: "O",
    memberVoucherGift: "M",
    previewReport: "T",
    paymentByAPAR: "A",
  },
  frontDeskAccessOrder: {
    accessForm: {
      dashboard: 0,
      floorPlan: 1,
      roomAvailability: 2,
      roomTypeAvailability: 3,
      roomAllotment: 4,
      guestProfile: 5,
      guestGroup: 6,
      reservation: 7,
      guestInHouse: 8,
      masterFolio: 9,
      deskFolio: 10,
      folioHistory: 11,
      transaction: 12,
      houseKeeping: 13,
      roomCosting: 14,
      guestLoanItem: 15,
      lostAndFound: 16,
      competitorData: 17,
      globalPostTransaction: 18,
      autoPostTransaction: 19,
      dayendClose: 20,
      company: 21,
      package: 22,
      roomRate: 23,
      dynamicRate: 24,
      roomRateLastDeal: 25,
    },
    accessReservation: {
      insert: 0,
      update: 1,
      void: 2,
      duplicate: 3,
      checkin: 4,
      cancel: 5,
      noshow: 6,
      deposit: 7,
      autoassign: 8,
      lock: 9,
      allotment: 10,
      keylock: 11,
      showAccessCheckInWithoutDeposit: 12,
    },
    accessDeposit: {
      void: 0,
      refund: 1,
      transfer: 2,
      insert: 3,
      cash: 4,
      card: 5,
      correction: 6,
      updateDocumentNumber: 7,
      updateRemark: 8,
      updateSubDepartment: 9,
      changeCorrectionDate: 10,
    },
    accessFloorPlan: {
      reception: 0,
      housekeeping: 1,
      modifyFloorPlan: 2,
    },
    accessKeylock: {
      canCheckInWithoutCard: 0,
      canCheckOutWithoutCard: 1,
      canIssuedCardMoreThanTwice: 2,
      canModifyArrivalDate: 3,
      canModifyDepartureDate: 4,
      canModifyDepartureTime: 5,
      departureDate1Night: 6,
      showAccessIssuedCardMoreThanOne: 7,
      canIssuedCardMoreThanOne: 8,
    },
    accessInHouse: {
      keylock: 0,
      transaction: 1,
      update: 2,
      moveRoom: 3,
      switchRoom: 4,
      cancelCheckIn: 5,
      message: 6,
      toDo: 7,
      lockFolio: 8,
      checkOut: 9,
      compliment: 10,
      houseUse: 11,
      walkIn: 12,
    },
    accessFolio: {
      void: 0,
      correction: 1,
      cashRefund: 2,
      transfer: 3,
      checkOut: 4,
      charge: 5,
      cash: 6,
      card: 7,
      directBill: 8,
      updateDirectBill: 9,
      otherPayment: 10,
      updateRemark: 11,
      updateDocumentNumber: 12,
      updateSubDepartment: 13,
      printFolio: 14,
      changeCorrectionDate: 15,
    },
    accessFolioHistory: {
      transaction: 0,
      printFolio: 1,
      cancelCheckOut: 2,
    },
    accessWalkIn: {
      breakdown: 0,
      extraCharge: 1,
      scheduledRate: 2,
    },
    accessMemberVoucherGift: {
      redeemPoint: 0,
      approveNotApproveVoucher: 1,
      insertVoucher: 2,
      soldVoucher: 3,
      redeemVoucher: 4,
      complimentVoucher: 5,
      deleteVoucher: 6,
    },
    accessSpecial: {
      voidReservation: 0,
      voidDeposit: 1,
      correctDeposit: 2,
      overrideRateOrDiscount: 3,
      maxPercent: 4,
      maxAmount: 5,
      modifyScheduleRate: 6,
      modifyBreakdown: 7,
      cancelCheckIn: 8,
      moveRoom: 9,
      voidSubFolio: 10,
      correctSubFolio: 11,
      cancelCheckOut: 12,
      modifyExtraCharge: 13,
      unlockReservation: 14,
      createMasterFolio: 15,
      modifyClosedJournal: 16,
      complimentGuest: 17,
      houseUseGuest: 18,
      // printInvoiceMoreThan: 19,
      transferToDeskFolio: 19,
      transferToMasterFolio: 20,
      businessSource: 21,
      decreaseStay: 22,
      updateInHouseGuestName: 23,
      checkInWithoutDepositReservation: 24,
    },
  },
  crmAccessOrder: {
    accessForm: {
      salesActivityDashboard: 0,
      salesActivity: 1,
      eventList: 2,
      phoneBook: 3,
      member: 4,
      voucher: 5,
      gift: 6,
      // TODO New Form
      proposalAndTaskCalendar: 7,
      activityLog: 8,
      //Guest Portal
      complaint: 9,
      feedback: 10,
    },
  },
  pointOfSalesAccessOrder: {
    accessForm: {
      customer: 0,
      reservation: 1,
      calendar: 2,
      transactionTerminal: 3,
      tableView: 4,
      spaRoomView: 5,
      iptvMenuOrder: 6,
      closedTransaction: 7,
      foodAndBeverageBudget: 8,
      dayendClose: 9,
      breakfastControl: 10,
      deskFolio: 11,
      folioHistory: 12,
      transaction: 13,
    },
    accessSpecial: {
      discount: 0,
      overridePrice: 1,
      modifyPrice: 2,
      voidCheck: 3,
      removeItem: 4,
      cancelCO: 5,
      voidReservation: 6,
      transferToDeskFolio: 7,
      transferToMasterFolio: 8,
      reduceQuantity: 9,
      addSpecialItem: 10,
    },
    accessTransactionTerminal: {
      changeQuantity: 0,
      discount: 1,
      overridePrice: 2,
      payment: 3,
      modifyPrice: 4,
      removeItem: 5,
      finishSale: 6,
      cancelCO: 7,
      addSpecialItem: 8,
      showOtherOutlet: 9,
    },
    accessTableView: {
      transfer: 0,
      tileTable: 1,
      savePosition: 2,
      adminMode: 3,
      takeAwayOrder: 4,
    },
  },
  accountingAccessOrder: {
    accessForm: {
      folioAndTransaction: 0,
      folioHistory: 1,
      receive: 2,
      payment: 3,
      prepaidExpense: 4,
      differedIncome: 5,
      receipt: 6,
      cheque: 7,
      journal: 8,
      incomeBudget: 9,
      expenseBudget: 10,
      statisticBudget: 11,
      manPowerBudget: 12,
      closeMonth: 13,
      closeYear: 14,
      dataAnalysis: 15,
      accountPayable: 16,
      apRefundDeposit: 17,
      apCommission: 18,
      accountReceivable: 19,
      arCityLedger: 20,
      arCityLedgerInvoice: 21,
      bankTransaction: 22,
      bankReconciliation: 23,
      cashReconciliation: 24,
      foreignCash: 25,
      auditTool: 26,
      sourceData: 27,
      journalNotBalance: 28,
      unsuccessfulExportJournal: 29,
    },
    accessSpecial: {
      modifyClosedJournal: 0,
      printInvoiceMoreThan: 1,
    },
    accessInvoice: {
      insert: 0,
      update: 1,
      delete: 2,
      insertPayment: 3,
      deletePayment: 4,
      printReceipt: 5,
      exchangeRate: 6,
      paymentByApAr: 7,
    },
  },
  inventoryAssetAccessOrder: {
    accessForm: {
      purchaseRequest: 0,
      purchaseOrder: 1,
      receiveStock: 2,
      storeRequisition: 3,
      stockTransfer: 4,
      costing: 5,
      costingPos: 6,
      production: 7,
      costRecipe: 8,
      returnStock: 9,
      stockOpname: 10,
      storeStock: 11,
      allStoreStock: 12,
      setActiveStock: 13,
      closeInventory: 14,
      faPurchaseOrder: 15,
      faReceive: 16,
      fixedAssetList: 17,
      linenManagement: 18,
      depreciation: 19,
    },
    accessInventoryReceive: {
      insert: 0,
      update: 1,
      delete: 2,
      receiveWithoutPo: 3,
    },
    accessFixedAssetReceive: {
      insert: 0,
      update: 1,
      delete: 2,
    },
    accessSpecial: {
      modifyClosedJournal: 0,
      acceptPurchaseRequest: 1,
      deletePurchaseOrder: 2,
      deletePurchaseRequest: 3,
    },
  },
  banquetAccessOrder: {
    accessForm: {
      booking: 0,
      banquetInProgress: 1,
      banquetView: 2,
      deskFolio: 3,
      folioHistory: 4,
    },
    userReportAccessOrder: {
      venue: 0,
      theme: 1,
      seatingPlan: 2,
      product: 3,
      package: 4,
      banquetBookingDetail: 5,
      banquetCalender: 6,
      banquetForecast: 7,
      banquetAdvancedDeposit: 8,
      banquetBalanceDeposit: 9,
      banquetChargeList: 10,
      banquetDailySales: 11,
      cancelBanquetReservation: 12,
      voidBanquetReservation: 13,
      cashierReport: 14,
      cashierReportReprint: 15,
      banquetBooking: 16,
    },
    userSpecialAccessOrder: {
      voidReservation: 0,
      voidReservationCharge: 1,
      voidDeposit: 2,
      correctDeposit: 3,
      voidSubFolio: 4,
      correctSubFolio: 5,
      cancelCheckIn: 6,
      cancelCheckOut: 7,
      createMasterFolio: 8,
      transferToDeskFolio: 9,
      transferToMasterFolio: 10,
    },
    userBookingAccessOrder: {
      insert: 0,
      update: 1,
      duplicate: 2,
      deposit: 3,
      cancel: 4,
      void: 5,
      noShow: 6,
      checkIn: 7,
    },
    userDepositAccessOrder: {
      insert: 0,
      cash: 1,
      card: 2,
      refund: 3,
      void: 4,
      correction: 5,
      transfer: 6,
      updateSubDepartment: 7,
      updateRemark: 8,
      updateDocumentNumber: 9,
    },
    userBanquetInProgressAccessOrder: {
      transaction: 0,
      insert: 1,
      update: 2,
      duplicate: 3,
      lockFolio: 4,
      cancelCheckIn: 5,
      checkOut: 6,
    },
    userWalkInAccessOrder: {
      scheduleRate: 0,
      breakdown: 1,
      extraCharge: 2,
    },
    userTransactionAccessOrder: {
      void: 0,
      correction: 1,
      cashRefund: 2,
      transfer: 3,
      checkOut: 4,
      charge: 5,
      cash: 6,
      card: 7,
      directBill: 8,
      updateDirectBill: 9,
      otherPayment: 10,
      updateRemark: 11,
      updateDocumentNumber: 12,
      updateSubDepartment: 13,
      printFolio: 14,
      changeCorrectionDate: 15,
    },
    userFolioHistoryAccessOrder: {
      transaction: 0,
      printFolio: 1,
      cancelCheckOut: 2,
    },
  },
  reportAccessOrder: {
    accessForm: {
      cashierReport: 0,
      frontDeskReport: 1,
      pointOfSalesReport: 2,
      banquetReport: 3,
      accountingReport: 4,
      inventoryAssetReport: 5,
    },
    accessPreviewReport: {
      editReport: 0,
      exportReport: 1,
      customizeReport: 2,
    },
  },
  toolsAccessOrder: {
    accessForm: {
      configuration: 0,
      setting: 1,
      userSetting: 2,
      userActivityLog: 3,
    },
    accessCompany: {
      insert: 0,
      update: 1,
      delete: 2,
      arLimit: 3,
      apLimit: 4,
      directBill: 5,
      businessSource: 6,
    },
    accessConfiguration: {
      department: 0,
      journalAccount: 1,
      bankAccount: 2,
    },
  },

  // Access user MenuOrder
  accessCHSMenuOrder: {
    dashboard: 0,
    floorPlan: 1,
    roomAvailability: 2,
    roomTypeAvailability: 3,
    roomAllotment: 4,
    guestProfile: 5,
    guestGroup: 6,
    reservation: 7,
    guestInHouse: 9,
    masterFolio: 10,
    deskFolio: 11,
    foliosAndTransaction: 12,
    folioHistory: 13,
    breakfastControl: 14,
    houseKeeping: 15,
    roomCosting: 16,
    guestLoanItem: 17,
    lostAndFound: 18,
    cashierReport: 19,
    competitorData: 20,
    globalPostTransaction: 21,
    autoPostTransaction: 22,
    dayendClose: 23,
    company: 24,
    package: 25,
    roomRate: 26,
    dynamicRate: 27,
    roomRateLastDeal: 28,
    salesActivity: 29,
    eventList: 30,
    phoneBook: 31,
    member: 32,
    voucher: 33,
    gift: 34,
  },

  accessCPOSMenuOrder: {
    transactionTerminal: 0,
    tableView: 1,
    spaRoomView: 2,
    iptvMenuOrder: 3,
    closedTransaction: 4,
    foodAndBeverageBudget: 5,
  },
  accessToolsMenuOrder: {
    configuration: 0,
    userSetting: 1,
    settings: 2,
    userActivityLog: 3,
  },
  accessReportMenuOrder: {
    cashierReport: 0,
    foReport: 1,
    posReport: 2,
    banReport: 3,
    accReport: 4,
    astReport: 5,
  },
  accessCASMenuOrder: {
    folioAndTransaction: 0,
    folioHistory: 1,
    receive: 2,
    payment: 3,
    prepaidExpense: 4,
    differedIncome: 5,
    receipt: 6,
    cheque: 7,
    journal: 8,
    incomeBudget: 9,
    expenseBudget: 10,
    statisticBudget: 11,
    manPowerBudget: 12,
    closeMonth: 13,
    closeYear: 14,
    //AP
    accountPayable: 15,
    apRefundDeposit: 16,
    apCommission: 17,
    //AR
    accountReceivable: 18,
    arCityLedger: 19,
    arCityLedgerInvoice: 20,
    bankTransaction: 21,
    bankReconciliation: 22,
    cashSalesReconciliation: 23,
    foreignCash: 24,
    //auditor
    auditTool: 25,
    sourceData: 26,
  },
  accessCAMSMenuOrder: {
    purchaseRequest: 0,
    purchaseOrder: 1,
    receiveStock: 2,
    storeRequisition: 3,
    stockTransfer: 4,
    costing: 5,
    costingPOS: 5,
    production: 6,
    costRecipe: 7,
    returnStock: 8,
    stockOpname: 9,
    storeStock: 10,
    allStoreStock: 11,
    setActiveStore: 12,
    closeInventory: 13,
    //FA
    faPurchaseOrder: 14,
    faReceive: 15,
    fixedAssetList: 16,
    linenManagement: 17,
    depreciation: 18,
  },
  accessCBSMenuOrder: {},
  accessGeneralOrder: {
    dashboard: 0,
    generalConfiguration: 1,
    chsConfiguration: 2,
    cposConfiguration: 3,
    cbsConfiguration: 4,
    casConfiguration: 5,
    camsConfiguration: 6,
    cashierReport: 7,
    userSetting: 8,
    userActivityLog: 9,
    oneTimePassword: 10,
    report: 11,
  },

  accessModule: {
    general: "G",
    hotel: "H",
    pointOfSales: "P",
    banquet: "B",
    accounting: "A",
    inventory: "I",
    report: "R",
    tools: "T",
    crm: "C",
    payroll: "PR",
  },
  // General:    "G",
  // Hotel:      "H",
  // Pos:        "P",
  // Banquet:    "B",
  // Accounting: "C",
  // Asset:      "A",
  // Payroll:    "R",
  // Corporate:  "0"}

  accessSpecialOrder: {
    unlockReservation: 1,
    voidReservation: 2,
    voidDeposit: 3,
    correctDeposit: 4,
    decreaseStay: 5,
    scheduledRate: 6,
    breakdown: 7,
    extraCharge: 8,
    complimentGuest: 9,
    houseUseGuest: 10,
    moveRoom: 11,
    voidSubFolio: 12,
    correctSubFolio: 13,
    cancelCheckIn: 14,
    cancelCheckOut: 15,
    createMasterFolio: 16,
    printMoreInvoice: 17,
    modifyClosedJournal: 18,
    transfertoDeskFolio: 19,
    transfertoMasterFolio: 20,
    businessSource: 21,
    overrideRateDiscount: 22,
    updateGuestName: 23,
    // pointOfSales
    reduceQuantity: 24,
    removeItem: 25,
    modifyPrice: 26,
    discount: 27,
    specialItem: 28,
    overridePrice: 29,
    cancelCaptainOrder: 30,
    voidCheck: 31,
  },
  specialAccessName: [
    "Unlock Reservation",
    "Void Reservation",
    "Void Deposit",
    "Correct Deposit",
    "Decrease Stay",
    "Scheduled Rate",
    "Breakdown",
    "Extra Charge",
    "Compliment Guest",
    "House Use Guest",
    "Move Room",
    "Void Sub Folio",
    "Correct Sub Folio",
    "Cancel Check In",
    "Cancel Check Out",
    "Create Master Folio",
    "Print More Invoice",
    "Modify Closed Journal",
    "Transfer to Desk Folio",
    "Transfer to Master Folio",
    "Business Source",
    "Override Rate/Discount",
  ],

  otherAccessOrder: {
    editReport: 0,
    exportReport: 1,
    customizeReport: 2,
    // deposit tool
    insertDeposit: 3,
    cashDeposit: 4,
    cardDeposit: 5,
    cashRefundDeposit: 6,
    voidDeposit: 7,
    correctionDeposit: 8,
    transferDeposit: 9,
    updateRemarkDeposit: 10,
    updateSubDepartmentDeposit: 11,
    updateDocumentNumberDeposit: 12,
    // folio transaction
    chargeTransaction: 13,
    cashTransaction: 14,
    cardTransaction: 15,
    directBillTransaction: 16,
    updateDirectBillTransaction: 17,
    cashRefundTransaction: 18,
    otherPaymentTransaction: 19,
    voidTransaction: 20,
    correctionTransaction: 21,
    transferTransaction: 22,
    updateSubDepartmentTransaction: 23,
    updateRemarkTransaction: 24,
    updateDocumentNumberTransaction: 25,
    checkOut: 26,
    printFolio: 27,
  },

  tableName: {
    accApAr: 0,
    accApArPayment: 1,
    accApArPaymentDetail: 2,
    accApCommissionPayment: 3,
    accApCommissionPaymentDetail: 4,
    accApRefundDepositPayment: 5,
    accApRefundDepositPaymentDetail: 6,
    accCashSaleRecon: 7,
    accCfgInitBankAccount: 8,
    accCloseMonth: 9,
    accCloseYear: 10,
    accConstBankAccountType: 11,
    accConstJournalGroup: 12,
    accConstJournalType: 13,
    accConstUnit: 14,
    accCreditCardRecon: 15,
    accCreditCardReconDetail: 16,
    accDefferedIncome: 17,
    accDefferedIncomePosted: 18,
    accForeignCash: 19,
    accImportJournalLog: 20,
    accJournal: 21,
    accJournalDetail: 22,
    accPrepaidExpense: 23,
    accPrepaidExpensePosted: 24,
    accReport: 25,
    accReportDefaultField: 26,
    accReportGroupingField: 27,
    accReportGroupField: 28,
    accReportOrderField: 29,
    accReportTemplate: 30,
    accReportTemplateField: 31,
    accUserGroup: 32,
    astCfgInitShippingAddress: 33,
    astConstPurchaseRequestStatus: 34,
    astConstStoreRequisitionStatus: 35,
    astReport: 36,
    astReportDefaultField: 37,
    astReportGroupingField: 38,
    astReportGroupField: 39,
    astReportOrderField: 40,
    astReportTemplate: 41,
    astReportTemplateField: 42,
    astUserGroup: 43,
    astUserSubDepartment: 44,
    auditLog: 45,
    banBooking: 46,
    banCfgInitSeatingPlan: 47,
    banCfgInitTheme: 48,
    banCfgInitVenue: 49,
    banCfgInitVenueCombine: 50,
    banCfgInitVenueCombineDetail: 51,
    banCfgInitVenueGroup: 52,
    banConstBookingStatus: 53,
    banConstReservationStatus: 54,
    banConstReservationType: 55,
    banConstVenueLocation: 56,
    banReport: 57,
    banReportDefaultField: 58,
    banReportGroupingField: 59,
    banReportGroupField: 60,
    banReportOrderField: 61,
    banReportTemplate: 62,
    banReportTemplateField: 63,
    banReservation: 64,
    banReservationCharge: 65,
    banReservationRemark: 66,
    banUserGroup: 67,
    breakfastListTemp: 68,
    budgetExpense: 69,
    budgetFb: 70,
    budgetIncome: 71,
    budgetStatistic: 72,
    cashCount: 73,
    cfgInitAccount: 74,
    cfgInitAccountSubGroup: 75,
    cfgInitBedType: 76,
    cfgInitBookingSource: 77,
    cfgInitCardBank: 78,
    cfgInitCardType: 79,
    cfgInitCity: 80,
    cfgInitCompanyType: 81,
    cfgInitCompetitorCategory: 82,
    cfgInitContinent: 83,
    cfgInitCountry: 84,
    cfgInitCreditCardCharge: 85,
    cfgInitCurrency: 86,
    cfgInitCurrencyNominal: 87,
    cfgInitCustomLookupField01: 88,
    cfgInitCustomLookupField02: 89,
    cfgInitCustomLookupField03: 90,
    cfgInitCustomLookupField04: 91,
    cfgInitCustomLookupField05: 92,
    cfgInitCustomLookupField06: 93,
    cfgInitCustomLookupField07: 94,
    cfgInitCustomLookupField08: 95,
    cfgInitCustomLookupField09: 96,
    cfgInitCustomLookupField10: 97,
    cfgInitCustomLookupField11: 98,
    cfgInitCustomLookupField12: 99,
    cfgInitDepartment: 100,
    cfgInitGuestType: 101,
    cfgInitIdCardType: 102,
    cfgInitIsFbSubDepartmentGroup: 103,
    cfgInitIsFbSubDepartmentGroupDetail: 104,
    cfgInitJournalAccount: 105,
    cfgInitJournalAccountCategory: 106,
    cfgInitJournalAccountSubGroup: 107,
    cfgInitLanguage: 108,
    cfgInitLoanItem: 109,
    cfgInitMarket: 110,
    cfgInitMarketCategory: 111,
    cfgInitMemberPointType: 112,
    cfgInitNationality: 113,
    cfgInitOwner: 114,
    cfgInitPabxRate: 115,
    cfgInitPackage: 116,
    cfgInitPackageBreakdown: 117,
    cfgInitPackageBusinessSource: 118,
    cfgInitPaymentType: 119,
    cfgInitPhoneBookType: 120,
    cfgInitPrinter: 121,
    cfgInitPurposeOf: 122,
    cfgInitRegency: 123,
    cfgInitReservationMark: 124,
    cfgInitRoom: 125,
    cfgInitRoomAllotmentType: 126,
    cfgInitRoomAmenities: 127,
    cfgInitRoomBoy: 128,
    cfgInitRoomRate: 129,
    cfgInitRoomRateBreakdown: 130,
    cfgInitRoomRateBusinessSource: 131,
    cfgInitRoomRateCategory: 132,
    cfgInitRoomRateCompetitor: 133,
    cfgInitRoomRateCurrency: 134,
    cfgInitRoomRateDynamic: 135,
    cfgInitRoomRateLastDeal: 136,
    cfgInitRoomRateScale: 137,
    cfgInitRoomRateSession: 138,
    cfgInitRoomRateSubCategory: 139,
    cfgInitRoomRateWeekly: 140,
    cfgInitRoomType: 141,
    cfgInitRoomUnavailableReason: 142,
    cfgInitRoomView: 143,
    cfgInitSales: 144,
    cfgInitState: 145,
    cfgInitSubDepartment: 146,
    cfgInitTaxAndService: 147,
    cfgInitTitle: 148,
    cfgInitVoucherReason: 149,
    cmNotification: 150,
    cmUpdate: 151,
    company: 152,
    competitor: 153,
    competitorData: 154,
    configuration: 155,
    constAccountGroup: 156,
    constBudgetType: 157,
    constChannelManagerVendor: 158,
    constChargeFrequency: 159,
    constChargeType: 160,
    constCommissionType: 161,
    constCustomerDisplayVendor: 162,
    constDepartmentType: 163,
    constDynamicRateType: 164,
    constFolioStatus: 165,
    constFolioType: 166,
    constForecastDay: 167,
    constForecastMonth: 168,
    constForeignCashTableId: 169,
    constGuestStatus: 170,
    constImage: 171,
    constIptvVendor: 172,
    constJournalAccountGroup: 173,
    constJournalAccountSubGroupType: 174,
    constJournalAccountType: 175,
    constJournalPrefix: 176,
    constKeylockVendor: 177,
    constMemberType: 178,
    constMikrotikVendor: 179,
    constNotificationType: 180,
    constOtherIcon: 181,
    constOtpStatus: 182,
    constPabxRateType: 183,
    constPaymentGroup: 184,
    constReportFont: 185,
    constReportFormat: 186,
    constReservationStatus: 187,
    constRoomBlockStatus: 188,
    constRoomStatus: 189,
    constSmsDestinationType: 190,
    constSmsRepeatType: 191,
    constStatisticAccount: 192,
    constSystem: 193,
    constTransactionType: 194,
    constUserAccessLevel: 195,
    constVoucherStatus: 196,
    constVoucherStatusApprove: 197,
    constVoucherStatusSold: 198,
    constVoucherType: 199,
    contactPerson: 200,
    corCfgInitUnit: 201,
    corReport: 202,
    corReportDefaultField: 203,
    corReportGroupingField: 204,
    corReportGroupField: 205,
    corReportOrderField: 206,
    corReportTemplate: 207,
    corReportTemplateField: 208,
    corUserGroup: 209,
    creditCard: 210,
    dataAnalysis: 211,
    dataAnalysisQuery: 212,
    dataAnalysisQueryList: 213,
    events: 214,
    faCfgInitItem: 215,
    faCfgInitItemCategory: 216,
    faCfgInitLocation: 217,
    faCfgInitManufacture: 218,
    faConstDepreciationType: 219,
    faConstItemCondition: 220,
    faConstLocationType: 221,
    faDepreciation: 222,
    faList: 223,
    faLocationHistory: 224,
    faPurchaseOrder: 225,
    faPurchaseOrderDetail: 226,
    faReceive: 227,
    faReceiveDetail: 228,
    faRepair: 229,
    faRevaluation: 230,
    fbStatistic: 231,
    folio: 232,
    folioRouting: 233,
    forecastInHouseChangePax: 234,
    forecastMonthlyDay: 235,
    forecastMonthlyDayPrevious: 236,
    generalUserGroup: 237,
    gridProperties: 238,
    guestBreakdown: 239,
    guestDeposit: 240,
    guestDetail: 241,
    guestExtraCharge: 242,
    guestExtraChargeBreakdown: 243,
    guestGeneral: 244,
    guestGroup: 245,
    guestInHouse: 246,
    guestInHouseBreakdown: 247,
    guestLoanItem: 248,
    guestMessage: 249,
    guestProfile: 250,
    guestRegistration: 251,
    guestScheduledRate: 252,
    guestToDo: 253,
    hotelInformation: 254,
    invoice: 255,
    invoiceItem: 256,
    invoicePayment: 257,
    invCfgInitItem: 258,
    invCfgInitItemCategory: 259,
    invCfgInitItemCategoryOtherCogs: 260,
    invCfgInitItemCategoryOtherCogs2: 261,
    invCfgInitItemCategoryOtherExpense: 262,
    invCfgInitItemGroup: 263,
    invCfgInitItemUom: 264,
    invCfgInitMarketList: 265,
    invCfgInitReturnStockReason: 266,
    invCfgInitStore: 267,
    invCfgInitUom: 268,
    invCloseLog: 269,
    invCloseSummary: 270,
    invCloseSummaryStore: 271,
    invCosting: 272,
    invCostingDetail: 273,
    invCostRecipe: 274,
    invOpname: 275,
    invProduction: 276,
    invPurchaseOrder: 277,
    invPurchaseOrderDetail: 278,
    invPurchaseRequest: 279,
    invPurchaseRequestDetail: 280,
    invReceiving: 281,
    invReceivingDetail: 282,
    invReturnStock: 283,
    invStockTransfer: 284,
    invStockTransferDetail: 285,
    invStoreRequisition: 286,
    invStoreRequisitionDetail: 287,
    log: 288,
    logBackup: 289,
    logKeylock: 290,
    logMode: 291,
    logShift: 292,
    logSpecialAccess: 293,
    logUser: 294,
    logUserAction: 295,
    logUserActionGroup: 296,
    lostAndFound: 297,
    marketStatistic: 298,
    member: 299,
    memberGift: 300,
    memberPoint: 301,
    memberPointRedeem: 302,
    notification: 303,
    notifTp: 304,
    notifTpCfgInitTemplate: 305,
    notifTpConstEvent: 306,
    notifTpConstVariable: 307,
    notifTpConstVendor: 308,
    oneTimePassword: 309,
    pabxSmdr: 310,
    phoneBook: 311,
    posCaptainOrder: 312,
    posCaptainOrderTransaction: 313,
    posCfgInitDiscountLimit: 314,
    posCfgInitMarket: 315,
    posCfgInitMemberOutletDiscount: 316,
    posCfgInitMemberOutletDiscountDetail: 317,
    posCfgInitMemberProductDiscount: 318,
    posCfgInitOutlet: 319,
    posCfgInitPaymentGroup: 320,
    posCfgInitProduct: 321,
    posCfgInitProductCategory: 322,
    posCfgInitProductGroup: 323,
    posCfgInitRoomBoy: 324,
    posCfgInitSpaRoom: 325,
    posCfgInitTable: 326,
    posCfgInitTableType: 327,
    posCfgInitTenan: 328,
    posCfgInitTherapistFingerprint: 329,
    posCfgInitWaitress: 330,
    posCheck: 331,
    posCheckTransaction: 332,
    posConstCheckType: 333,
    posConstComplimentType: 334,
    posConstDiscount: 335,
    posConstTimeSegment: 336,
    posInformation: 337,
    posIptvMenuOrder: 338,
    posMember: 339,
    posProductCosting: 340,
    posReport: 341,
    posReportDefaultField: 342,
    posReportGroupingField: 343,
    posReportGroupField: 344,
    posReportOrderField: 345,
    posReportTemplate: 346,
    posReportTemplateField: 347,
    posReservation: 348,
    posReservationTable: 349,
    posTableUnavailable: 350,
    posUserGroup: 351,
    posUserGroupOutlet: 352,
    proformaInvoiceDetail: 353,
    receipt: 354,
    report: 355,
    reportCustom: 356,
    reportCustomFavorite: 357,
    reportDefaultField: 358,
    reportGroupingField: 359,
    reportGroupField: 360,
    reportOrderField: 361,
    reportPivotTemp: 362,
    reportRoomRateStructureTemp: 363,
    reportRoomSales: 364,
    reportTemplate: 365,
    reportTemplateField: 366,
    reportUserGroup: 367,
    reservation: 368,
    reservationExtraCharge: 369,
    reservationExtraChargeBreakdown: 370,
    reservationScheduledRate: 371,
    roomAllotment: 372,
    roomStatistic: 373,
    roomStatus: 374,
    roomUnavailable: 375,
    roomUnavailableHistory: 376,
    salActivity: 377,
    salActivityLog: 378,
    salCfgInitSegment: 379,
    salCfgInitSource: 380,
    salCfgInitTaskAction: 381,
    salCfgInitTaskRepeat: 382,
    salCfgInitTaskTag: 383,
    salCfgInitTemplate: 384,
    salConstProposalStatus: 385,
    salConstResource: 386,
    salConstStatus: 387,
    salConstTaskPriority: 388,
    salConstTaskStatus: 389,
    salContact: 390,
    salNotes: 391,
    salProposal: 392,
    salSendReminder: 393,
    salTask: 394,
    smsEvent: 395,
    smsOutbox: 396,
    smsSchedule: 397,
    subFolio: 398,
    subFolioGroup: 399,
    tempSubFolioBreakdown1: 400,
    tempSubFolioCorrectionBreakdown: 401,
    toolsUserGroup: 402,
    user: 403,
    userGroup: 404,
    userGroupAccess: 405,
    voucher: 406,
    workingShift: 407,
    unsuccessfulExportJournal: 408,
  },

  responseStatus: {
    successfully: 0,
    notAuthorized: 1,
    invalidDataFormat: 2,
    errorCreateToken: 3,
    dataNotFound: 4,
    invalidDataValue: 5,
    databaseValueChanged: 6,
    databaseError: 7,
    emptyRequireField: 8,
    paymentDateCannotLowerThanIssuedDate: 9,
    successfullyWithStatus: 10,
    duplicateEntry: 11,
    subscriptionExpired: 12,
    unregistered: 13,
    otherResult: 999,
  },
  wsMessageType: {
    broadcast: 1,
    channel: 2,
    client: 3,
    connection: 4,
    room: 5,
  },
  wsDataType: {
    serverStatus: 1,
    dayendCloseStatus: 2,
    modifiedRoomAvailabilityStatus: 3,
    auditDate: 4,
    announcement: 5,
    runningText: 6,
    databaseUpdateStatus: 7,
  },
  systemCode: {
    General: "G",
    Hotel: "H",
    Pos: "P",
    Banquet: "B",
    Accounting: "A",
    Asset: "I",
    Payroll: "R",
    Corporate: "0",
    Report: "R",
    Tools: "T",
  },

  keylockVendor: {
    Ventaza: "VENT",
    UltraLock: "ULTR",
    DLock: "DLOC",
    DLockOldVersion: "DLOL",
    Kiara: "KIAR",
    Colcom: "COLC",
    SureLock: "SURE",
    Deluns: "DLUN",
    Kima: "KIMA",
    HuneLock: "HUNE",
    VingCard: "VING",
    SunVitio: "SUNV",
    Rafles: "RAFE",
    BeTech: "BTEC",
    OnityOld: "ONOL",
    Saflok: "SAFL",
    ColcomOld: "COLO",
    Tesa: "TESA",
    VingcardVisionline: "VISI",
    CLock: "CAKR",
    Downs: "DOWN",
    Onity: "ONIT",
    OnityOldVersion: "ONIO",
    VingCardSerial: "VISE",
    Kaba: "KABA",
    RaflesUSB: "RAUS",
    Miwa: "MIWA",
    Saflokv2: "SAF2",
    OnityV2: "ONI2",
    OnityX: "ONIX",
  },
  mikrotikVendor: {
    Mikrotik: "MIKR",
    Megalos: "MEGA",
    Provenos: "PROV",
    Coova: "COOV",
  },
  channelManager: {
    BookNLink: "BKNL",
    Stah: "STAH",
    SiteMinder: "STMD",
  },
  pmsCommand: {
    Issued: "I",
    Verified: "V",
    Replaced: "R",
    Erase: "E",
    Deactivated: "D",
    ForceErase: "F",
  },
};
