import $global from "@/utils/global";
const accessMenuOrder = $global.accountingAccessOrder.accessForm;
const mainPath = "/accounting";
export default [
  {
    name: "labels.transaction",
    isParent: true,
    children: [
      {
        name: "labels.receive",
        componentName: "receive",
        path: mainPath + "/receive",
        cIcon: "receive",
        routeOrder: accessMenuOrder.receive,
        requiresAuth: true,
      },
      {
        name: "labels.payment",
        componentName: "payment",
        path: mainPath + "/payment",
        cIcon: "payment",
        routeOrder: accessMenuOrder.payment,
        requiresAuth: true,
      },
      {
        name: "labels.prepaidExpense",
        componentName: "prepaid_expense",
        path: mainPath + "/prepaid-expense",
        cIcon: "prepaid_expense",
        routeOrder: accessMenuOrder.prepaidExpense,
        requiresAuth: true,
      },
      {
        name: "labels.differedIncome",
        componentName: "deferred_income",
        path: mainPath + "/differed-income",
        cIcon: "deferred_income",
        routeOrder: accessMenuOrder.differedIncome,
        requiresAuth: true,
      },
      {
        name: "labels.receipt",
        componentName: "receipt",
        path: mainPath + "/receipt",
        cIcon: "receipt",
        routeOrder: accessMenuOrder.receipt,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.journal",
    isParent: true,
    children: [
      {
        name: "labels.journal",
        componentName: "journal",
        path: mainPath + "/journal",
        cIcon: "journal",
        routeOrder: accessMenuOrder.journal,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.budget",
    isParent: true,
    children: [
      {
        name: "labels.incomeBudget",
        componentName: "income_budget",
        path: mainPath + "/income-budget",
        cIcon: "income_budget",
        routeOrder: accessMenuOrder.incomeBudget,
        requiresAuth: true,
      },
      {
        name: "labels.expenseBudget",
        componentName: "expense_budget",
        path: mainPath + "/expense-budget",
        cIcon: "expense_budget",
        routeOrder: accessMenuOrder.expenseBudget,
        requiresAuth: true,
      },
      {
        name: "labels.statisticBudget",
        componentName: "statistic_budget",
        path: mainPath + "/statistic-budget",
        cIcon: "statistic_budget",
        routeOrder: accessMenuOrder.statisticBudget,
        requiresAuth: true,
      },
      {
        name: "labels.manPower",
        componentName: "man_power",
        path: mainPath + "/man-power",
        cIcon: "man_power",
        routeOrder: accessMenuOrder.manPowerBudget,
        hidden: true,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.closingTool",
    isParent: true,
    children: [
      {
        name: "labels.closeMonth",
        componentName: "close_month",
        path: mainPath + "/close-month",
        cIcon: "close_month",
        routeOrder: accessMenuOrder.closeMonth,
        requiresAuth: true,
      },
      {
        name: "labels.closeYear",
        componentName: "close_year",
        path: mainPath + "/close-year",
        cIcon: "close_year",
        routeOrder: accessMenuOrder.closeYear,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.accountPayable",
    isParent: true,
    children: [
      {
        name: "labels.accountPayable",
        componentName: "account_payable",
        path: mainPath + "/account-payable",
        cIcon: "account_payable",
        routeOrder: accessMenuOrder.accountPayable,
        requiresAuth: true,
      },
      {
        name: "labels.apRefundDeposit",
        componentName: "ap_refund_deposit",
        path: mainPath + "/ap-refund-deposit",
        cIcon: "ap_refund_deposit",
        routeOrder: accessMenuOrder.apRefundDeposit,
        requiresAuth: true,
      },
      {
        name: "labels.apCommission",
        componentName: "ap_commission",
        path: mainPath + "/ap-commission-other",
        cIcon: "ap_commission",
        routeOrder: accessMenuOrder.apCommission,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.accountReceivable",
    isParent: true,
    children: [
      {
        name: "labels.accountReceivable",
        componentName: "account_receivable",
        path: mainPath + "/account-receivable",
        cIcon: "account_receivable",
        routeOrder: accessMenuOrder.accountReceivable,
        requiresAuth: true,
      },
      {
        name: "labels.arCityLedger",
        componentName: "ar_city_ledger",
        path: mainPath + "/ar-city-ledger",
        cIcon: "ar_city_ledger",
        routeOrder: accessMenuOrder.arCityLedger,
        requiresAuth: true,
      },
      {
        name: "labels.arCityLedgerInvoice",
        componentName: "ar_city_ledger_invoice",
        path: mainPath + "/ar-city-ledger-invoice",
        cIcon: "ar_city_ledger_invoice",
        routeOrder: accessMenuOrder.arCityLedgerInvoice,
        requiresAuth: true,
      },
      {
        name: "labels.bankTransaction",
        componentName: "bank_transaction",
        path: mainPath + "/bank-transaction",
        cIcon: "bank_transaction",
        routeOrder: accessMenuOrder.bankTransaction,
        requiresAuth: true,
      },
      {
        name: "labels.bankReconciliation",
        componentName: "bank_reconciliation",
        path: mainPath + "/bank-reconciliation",
        cIcon: "bank_reconciliation",
        routeOrder: accessMenuOrder.bankReconciliation,
        requiresAuth: true,
      },
      {
        name: "labels.cashSalesReconciliation",
        componentName: "cash_sales_reconciliation",
        path: mainPath + "/cash-sales-reconciliation",
        cIcon: "cash_sales_reconciliation",
        routeOrder: accessMenuOrder.cashReconciliation,
        requiresAuth: true,
      },
      // ++++++++++++++++++++
      {
        name: "labels.foreignCash",
        componentName: "foreign_cash",
        path: mainPath + "/foreign-cash",
        cIcon: "foreign_cash",
        routeOrder: accessMenuOrder.foreignCash,
        hidden: true,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.auditor",
    isParent: true,
    children: [
      {
        name: "labels.journalNotBalance",
        componentName: "journal_not_balance",
        path: mainPath + "/journal-not-balance",
        cIcon: "auditor",
        routeOrder: accessMenuOrder.journalNotBalance,
        requiresAuth: true,
      },
      {
        name: "labels.unsuccessfulExportJournal",
        componentName: "unsuccessful_export_journal",
        path: mainPath + "/unsuccessful-export-journal",
        cIcon: "auditor",
        routeOrder: accessMenuOrder.unsuccessfulExportJournal,
        requiresAuth: true,
      },
    ],
  },
  // {
  //   name: "labels.auditTool",
  //   path: mainPath+"/audit-tool",
  //   routeOrder: accessMenuOrder.auditTool,
  //   requiresAuth: true,
  // },
];
