import $global from "@/utils/global";
const accessMenuOrder = $global.inventoryAssetAccessOrder.accessForm;
const mainPath = "/assets";
export default [
  {
    name: "labels.management",
    isParent: true,
    children: [
      {
        name: "labels.purchaseRequest",
        componentName: "purchase_request",
        path: mainPath + "/purchase-request",
        routeOrder: accessMenuOrder.purchaseRequest,
        cIcon: "purchase_request",
        requiresAuth: true,
      },
      {
        name: "labels.purchaseOrder",
        componentName: "purchase_order",
        path: mainPath + "/purchase-order",
        routeOrder: accessMenuOrder.purchaseOrder,
        cIcon: "purchase_order",
        requiresAuth: true,
      },
      {
        name: "labels.receiveStock",
        componentName: "receiving",
        path: mainPath + "/receive-stock",
        routeOrder: accessMenuOrder.receiveStock,
        cIcon: "receiving",
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.transaction",
    isParent: true,
    children: [
      {
        name: "labels.storeRequisition",
        componentName: "store_requisition",
        path: mainPath + "/store-requisition",
        routeOrder: accessMenuOrder.storeRequisition,
        cIcon: "store_requisition",
        requiresAuth: true,
      },
      {
        name: "labels.stockTransfer",
        componentName: "stock_transfer",
        path: mainPath + "/stock-transfer",
        routeOrder: accessMenuOrder.stockTransfer,
        cIcon: "stock_transfer",
        requiresAuth: true,
      },
      {
        name: "labels.costing",
        componentName: "costing",
        path: mainPath + "/costing",
        routeOrder: accessMenuOrder.costing,
        cIcon: "costing",
        requiresAuth: true,
      },
      {
        name: "labels.costingPos",
        componentName: "costing_pos",
        path: mainPath + "/costing-pos",
        routeOrder: accessMenuOrder.costingPos,
        cIcon: "costing_pos",
        requiresAuth: true,
      },
      {
        name: "labels.production",
        componentName: "production",
        path: mainPath + "/production",
        routeOrder: accessMenuOrder.production,
        cIcon: "production",
        requiresAuth: true,
      },
      {
        name: "labels.costRecipe",
        componentName: "cost_recipe",
        path: mainPath + "/cost-recipe",
        routeOrder: accessMenuOrder.costRecipe,
        cIcon: "cost_recipe",
        requiresAuth: true,
      },
      {
        name: "labels.returnStock",
        componentName: "return_stock",
        path: mainPath + "/return-stock",
        routeOrder: accessMenuOrder.returnStock,
        cIcon: "return_stock",
        requiresAuth: true,
      },
      {
        name: "labels.stockOpname",
        componentName: "stock_opname",
        path: mainPath + "/stock-opname",
        routeOrder: accessMenuOrder.stockOpname,
        cIcon: "stock_opname",
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.stock",
    isParent: true,
    children: [
      {
        name: "labels.storeStock",
        componentName: "store_stock",
        path: mainPath + "/store-stock",
        routeOrder: accessMenuOrder.storeStock,
        cIcon: "store_stock",
        requiresAuth: true,
      },
      {
        name: "labels.allStoreStock",
        componentName: "all_store_stock",
        path: mainPath + "/all-store-stock",
        routeOrder: accessMenuOrder.allStoreStock,
        cIcon: "all_store_stock",
        requiresAuth: true,
      },
      {
        name: "labels.closeInventory",
        componentName: "close_inventory",
        path: mainPath + "/close-inventory",
        routeOrder: accessMenuOrder.closeInventory,
        cIcon: "close_inventory",
        requiresAuth: true,
      },
    ],
  },

  {
    name: "labels.fixedAsset",
    isParent: true,
    children: [
      {
        name: "labels.faPurchaseOrder",
        componentName: "fa_purchase_order",
        path: mainPath + "/fa-purchase-order",
        routeOrder: accessMenuOrder.faPurchaseOrder,
        cIcon: "fa_purchase_order",
        requiresAuth: true,
      },
      {
        name: "labels.faReceive",
        componentName: "fa_receive",
        path: mainPath + "/fa-receive",
        routeOrder: accessMenuOrder.faReceive,
        cIcon: "fa_receive",
        requiresAuth: true,
      },
      {
        name: "labels.fixedAssetList",
        componentName: "fa_asset_list",
        path: mainPath + "/fixed-asset-list",
        routeOrder: accessMenuOrder.fixedAssetList,
        cIcon: "fa_list",
        requiresAuth: true,
      },
      {
        name: "labels.linenManagement",
        componentName: "linen_management",
        path: mainPath + "/linen-management",
        routeOrder: accessMenuOrder.linenManagement,
        cIcon: "linen_management",
        requiresAuth: true,
      },
      {
        name: "labels.depreciation",
        componentName: "depreciation",
        path: mainPath + "/depreciation",
        routeOrder: accessMenuOrder.depreciation,
        cIcon: "depreciation",
        requiresAuth: true,
      },
    ],
  },
  // =====================
];
