import $global from "@/utils/global";
const accessMenuOrder = $global.frontDeskAccessOrder.accessForm;
const mainPath = "/front-desk";
export default [
  {
    name: "labels.general",
    isParent: true,
    children: [
      {
        name: "labels.floorPlan",
        componentName: "floor_plan",
        path: mainPath + "/floor-plan",
        cIcon: "floor_plan",
        routeOrder: accessMenuOrder.floorPlan,
        requiresAuth: true,
      },
      {
        name: "labels.roomAvailability",
        componentName: "room_availability",
        path: mainPath + "/room-availability",
        cIcon: "room_availability",
        routeOrder: accessMenuOrder.roomAvailability,
        requiresAuth: true,
      },
      {
        name: "labels.roomTypeAvailability",
        componentName: "room_type_availability",
        path: mainPath + "/room-type-availability",
        cIcon: "room_type_availability",
        routeOrder: accessMenuOrder.roomTypeAvailability,
        requiresAuth: true,
      },
      {
        name: "labels.roomAllotment",
        componentName: "room_allotment",
        path: mainPath + "/room-allotment",
        cIcon: "room_allotment",
        routeOrder: accessMenuOrder.roomAllotment,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.reservation",
    routeOrder: accessMenuOrder.reservation,
    isParent: true,
    children: [
      {
        name: "labels.reservation",
        path: mainPath + "/reservation",
        componentName: "reservation",
        cIcon: "reservation",
        routeOrder: accessMenuOrder.reservation,
        requiresAuth: true,
      },
      {
        name: "labels.guestGroup",
        path: mainPath + "/guest-group",
        componentName: "guest_group",
        cIcon: "guest_group",
        routeOrder: accessMenuOrder.guestGroup,
        requiresAuth: true,
      },
      {
        name: "labels.guestProfile",
        path: mainPath + "/guest-profile",
        componentName: "guest_profile",
        cIcon: "guest_profile",
        routeOrder: accessMenuOrder.guestProfile,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.folio",
    isParent: true,
    children: [
      {
        name: "labels.guestInHouse",
        path: mainPath + "/guest-in-house",
        componentName: "guest_in_house",
        cIcon: "guest_in_house",
        routeOrder: accessMenuOrder.guestInHouse,
        requiresAuth: true,
      },
      {
        name: "labels.masterFolio",
        path: mainPath + "/master-folio",
        componentName: "master_folio",
        cIcon: "master_folio",
        routeOrder: accessMenuOrder.masterFolio,
        requiresAuth: true,
      },
      {
        name: "labels.deskFolio",
        path: mainPath + "/desk-folio",
        componentName: "desk_folio",
        cIcon: "desk_folio",
        routeOrder: accessMenuOrder.deskFolio,
        requiresAuth: true,
      },
      {
        name: "labels.folioHistory",
        path: mainPath + "/folio-history",
        componentName: "folio_history",
        cIcon: "folio_history",
        routeOrder: accessMenuOrder.folioHistory,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.housekeeping",
    isParent: true,
    children: [
      {
        name: "labels.housekeeping",
        path: mainPath + "/housekeeping",
        componentName: "housekeeping",
        cIcon: "housekeeping",
        routeOrder: accessMenuOrder.houseKeeping,
        requiresAuth: true,
      },
      {
        name: "labels.lostAndFound",
        path: mainPath + "/lost-and-found",
        componentName: "lost_and_found",
        cIcon: "lost_and_found",
        routeOrder: accessMenuOrder.lostAndFound,
        requiresAuth: true,
      },
      {
        name: "title.guestLoanItem",
        path: mainPath + "/guest-loan-item",
        componentName: "guest_loan_item",
        cIcon: "guest_loan_item",
        routeOrder: accessMenuOrder.guestLoanItem,
        requiresAuth: true,
      },
    ],
  },

  {
    name: "labels.nightAudit",
    isParent: true,
    children: [
      {
        name: "labels.competitorData",
        path: mainPath + "/competitor-data",
        componentName: "competitor_data",
        cIcon: "competitor_data",
        routeOrder: accessMenuOrder.competitorData,
        requiresAuth: true,
      },
      {
        name: "labels.autoPostTransaction",
        path: mainPath + "/auto-post-transaction",
        componentName: "auto_post_transaction",
        cIcon: "auto_post_transaction",
        routeOrder: accessMenuOrder.autoPostTransaction,
        requiresAuth: true,
      },
      {
        name: "labels.dayendClose",
        path: mainPath + "/dayend-close",
        componentName: "dayend_close",
        cIcon: "dayend_close",
        routeOrder: accessMenuOrder.dayendClose,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.marketing",
    isParent: true,
    children: [
      {
        name: "labels.roomRate",
        path: "/tools/configurations/room-rate",
        componentName: "room_rate",
        cIcon: "room_rate",
        routeOrder: accessMenuOrder.roomRate,
        requiresAuth: true,
      },
      {
        name: "labels.dynamicRate",
        path: mainPath + "/dynamic-rate",
        componentName: "dynamic_rate",
        cIcon: "dynamic_rate",
        routeOrder: accessMenuOrder.dynamicRate,
        requiresAuth: true,
      },
      {
        name: "labels.roomRateLastDeal",
        path: mainPath + "/room-rate-last-deal",
        componentName: "room_rate_last_deal",
        cIcon: "room_rate_last_deal",
        routeOrder: accessMenuOrder.roomRateLastDeal,
        requiresAuth: true,
      },
    ],
  },
];
