import $global from "@/utils/global";
const accessMenuOrder = $global.crmAccessOrder.accessForm;
const mainPath = "/payroll";
export default [
  {
    name: "labels.training",
    isParent: true,
    children: [
      {
        name: "labels.training",
        path: mainPath + "/training",
        componentName: "training",
        cIcon: "training",
        routeOrder: 1,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.payroll.employee.management",
    isParent: true,
    children: [
      {
        name: "labels.payroll.employee.employee",
        componentName: "employee",
        path: mainPath + "/employee",
        cIcon: "employee",
        routeOrder: 2,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.employee.salaryHistory",
        componentName: "salary_history",
        path: mainPath + "/salary-history",
        cIcon: "salary_history",
        routeOrder: 3,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.employee.employeeDocument",
        componentName: "employee_document",
        path: mainPath + "/employee-document",
        cIcon: "employee_document",
        routeOrder: 4,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.employee.organization",
        componentName: "organization",
        path: mainPath + "/organization",
        cIcon: "organization",
        routeOrder: 5,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.payroll.attendance.attendanceAndLeave",
    isParent: true,
    children: [
      {
        name: "labels.payroll.attendance.attendance",
        componentName: "attendance",
        path: mainPath + "/attendance",
        cIcon: "attendance",
        routeOrder: 6,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.attendance.attendanceEntry",
        componentName: "attendance_entry",
        path: mainPath + "/attendance-entry",
        cIcon: "attendance_entry",
        routeOrder: 7,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.attendance.leaveApplication",
        componentName: "leave_application",
        path: mainPath + "/leave-application",
        cIcon: "leave_application",
        routeOrder: 8,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.attendance.leaveApproval",
        componentName: "leave_approval",
        path: mainPath + "/leave-approval",
        cIcon: "leave_approval",
        routeOrder: 9,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.attendance.workSchedule",
        componentName: "work_schedule",
        path: mainPath + "/work-schedule",
        cIcon: "work_schedule",
        routeOrder: 10,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.attendance.holidayCalender",
        componentName: "holiday_calender",
        path: mainPath + "/holiday_calender",
        cIcon: "holiday_calender",
        routeOrder: 11,
        requiresAuth: true,
      },
    ],
  },
  {
    name: "labels.payroll.payroll.payroll",
    isParent: true,
    children: [
      {
        name: "labels.payroll.payroll.payrollPeriod",
        componentName: "payroll_period",
        path: mainPath + "/payroll-period",
        cIcon: "payroll_period",
        routeOrder: 12,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.payroll.payrollApproval",
        componentName: "payroll_approval",
        path: mainPath + "/payroll-approval",
        cIcon: "payroll_approval",
        routeOrder: 13,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.payroll.payrollDisbursement",
        componentName: "payroll_disbursement",
        path: mainPath + "/payroll-disbursement",
        cIcon: "payroll_disbursement",
        routeOrder: 14,
        requiresAuth: true,
      },
      {
        name: "labels.payroll.payroll.payrollComponent",
        componentName: "payroll_component",
        path: mainPath + "/payroll-component",
        cIcon: "payroll_component",
        routeOrder: 15,
        requiresAuth: true,
      },
    ],
  },
  // {
  //   name: "labels.reimbursement",
  //   isParent: true,
  //   children: [
  //     {
  //       name: "labels.reimbursementApplication",
  //       componentName: "reimbursement_application",
  //       path: mainPath + "/reimbursement-application",
  //       cIcon: "reimbursement_application",
  //       routeOrder: 14,
  //       requiresAuth: true,
  //     },
  //     {
  //       name: "labels.reimbursementApproval",
  //       componentName: "reimbursement_approval",
  //       path: mainPath + "/reimbursement-approval",
  //       cIcon: "reimbursement_approval",
  //       routeOrder: 15,
  //       requiresAuth: true,
  //     },
  //     {
  //       name: "labels.reimbursementHistory",
  //       componentName: "reimbursement_history",
  //       path: mainPath + "/reimbursement-history",
  //       cIcon: "reimbursement_history",
  //       routeOrder: 16,
  //       requiresAuth: true,
  //     },
  //   ],
  // },
  // {
  //   name: "labels.cashAdvanceAndLoan",
  //   isParent: true,
  //   children: [
  //     {
  //       name: "labels.loanApplication",
  //       componentName: "loan_application",
  //       path: mainPath + "/loan-application",
  //       cIcon: "loan_application",
  //       routeOrder: 17,
  //       requiresAuth: true,
  //     },
  //     {
  //       name: "labels.loanApproval",
  //       componentName: "loan_approval",
  //       path: mainPath + "/loan-approval",
  //       cIcon: "loan_approval",
  //       routeOrder: 18,
  //       requiresAuth: true,
  //     },
  //     {
  //       name: "labels.loanInstallment",
  //       componentName: "loan_installment",
  //       path: mainPath + "/loan-installment",
  //       cIcon: "loan_installment",
  //       routeOrder: 19,
  //       requiresAuth: true,
  //     },
  //   ],
  // },
];
